dist: trusty
language: php

php:
    - 7.3
    - 7.4

cache:
    directories:
        - $HOME/.composer/cache

jobs:
    include:
        -   php: 7.3
            env: 'COMPOSER_FLAGS="--prefer-stable --prefer-lowest"'

before_script:
    - travis_retry composer update ${COMPOSER_FLAGS} --no-interaction --prefer-dist

script:
    - vendor/bin/phpunit
